### ISSUE TITLE
Explore and test remaining safety tests can make use of pharmaverseadam data 

### ISSUE THREAD

**Issue by khatril** [insightsengineering/scda.test#133]
Remaining safety domains: Exposure, ECG, VS

- [x] [test-listing_cml01.R
- [x] test-listing_cml02a_gl.R
- [x] test-listing_cml02b_gl.R
- [x] test-listing_egl01.R
- [x] test-listing_exl01.R
- [x] test-table_cmt01.R
- [x] test-table_cmt01a.R
- [x] test-table_cmt01b.R
- [x] test-table_cmt02_pt.R

**Comment by khatril** [comment]
@zdz2101 Is this something you have capacity to look at? Thanks!

**Comment by edelarua** [comment]
@shajoezhu 

Missing variables:

adcm
- `CMENRTPT` (CML01)
- `ATIREL` (CMT01, CMT01A, CMT01B)
- `ATC1` (CML02B_GL, CMT01B)
- `ATC2` (CML02A_GL, CML02B_GL, CMT01A, CMT01B)
- `ATC3` (CML02B_GL, CMT01B)
- `ATC4` (CML02B_GL, CMT01B)

adeg
- `AVALU` - could use `EGSTRESU` as a substitute (EGL01)

adex
- `AVALU` (EXL01)

**Comment by khatril** [comment]
@edelarua @shajoezhu let's raise an issue in pharmaverseadam for the following in ADCM:
ADCM we could request CMENRTPT, ATCx variables

In both datasets for AVALU we can ask if its possible, or add in our pre-processing steps

**Comment by edelarua** [comment]
> @edelarua @shajoezhu let's raise an issue in pharmaverseadam for the following in ADCM: ADCM we could request CMENRTPT, ATCx variables
> 
> In both datasets for AVALU we can ask if its possible, or add in our pre-processing steps

@khatril @shajoezhu do you want to open the issue or shall I? See also [my comment](https://github.com/insightsengineering/scda.test/issues/147#issuecomment-2248951465) on part 2 of the safety testing issue.

**Comment by shajoezhu** [comment]
thanks so much Em!
