### ISSUE TITLE
Explore and test remaining safety can make use of pharmaverseadam part 2

### ISSUE THREAD

**Issue by khatril** [insightsengineering/scda.test#147]
- [x]  test-table_egt01.R
- [x]  test-table_egt02.R
- [x]  test-table_egt03.R
- [x]  test-table_egt04.R
- [x]  test-table_egt05_qtcat.R
- [x]  test-table_ext01.R
- [x]  test-table_vst01.R
- [x]  test-table_vst02.R

**Comment by edelarua** [comment]
Missing variables:

adeg
- `WORS02FL` (egt04)

adex
- `PARCAT2` (ext01)
